default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  port:  <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  reaping_frequency: 10

test:
  <<: *default
  database: <%= ENV['DB_NAME_TEST'] || 'itechservice_test' %>

staging:
  <<: *default

production:
  <<: *default