#{:id => 162, :name => "iPhone iPhone 4S White 16GB"},
#{:id => 164, :name => "iPhone iPhone 4 Black 16GB"},
#{:id => 166, :name => "iPhone iPhone 4 White 16GB"},
#{:id => 167, :name => "iPhone iPhone 4S Black 64GB"},
#{:id => 171, :name => "iPhone iPhone 5 White 16GB"},
#{:id => 172, :name => "iPad iPad 3 (New iPad)  Wi-Fi + Cellular Black 32GB"},
#{:id => 173, :name => "iPhone iPhone 4S Black 32GB"},
DEVICE_TYPES = [
{:id => 179, :name => "iPhone iPhone 2G 8GB"},
{:id => 180, :name => "iPhone iPhone 5 Black 32GB"},
{:id => 184, :name => "iPhone iPhone 5 Black 64GB"},
{:id => 185, :name => "iPad iPad 4 (with Retina Display) Wi-Fi White 32GB"},
{:id => 187, :name => "iPhone iPhone 4S White 32GB"},
{:id => 188, :name => "Mac MacBook Pro"},
{:id => 191, :name => "iPhone iPhone 4S White 64GB"},
{:id => 192, :name => "iPad iPad 2 Wi-Fi + Cellular White 64Gb"},
{:id => 194, :name => "iPad iPad 4 (with Retina Display) Wi-Fi + Cellular Black 64GB"},
{:id => 196, :name => "iPhone iPhone 4 Black 8GB"},
{:id => 197, :name => "iPhone iPhone 4 White 32GB"},
{:id => 198, :name => "iPhone iPhone 5 White 64GB"},
{:id => 199, :name => "iPad iPad 2 Wi-Fi + Cellular Black 16GB"},
{:id => 200, :name => "iPhone iPhone 5 White None"},
{:id => 201, :name => "iPad iPad 3 (New iPad)  Wi-Fi + Cellular White 64GB"},
{:id => 203, :name => "iPad iPad 4 (with Retina Display) Wi-Fi + Cellular White 32GB"},
{:id => 204, :name => "iPhone iPhone 5 White 32GB"},
{:id => 205, :name => "iPad iPad 2 Wi-Fi White  16GB"},
{:id => 206, :name => "iPhone iPhone 4S Black 16GB"},
{:id => 207, :name => "iPhone iPhone 4 Black 32GB"},
{:id => 208, :name => "iPad iPad 2 Wi-Fi + Cellular Black 64GB"},
{:id => 209, :name => "iPhone iPhone 3GS White 32GB"},
{:id => 210, :name => "iPad iPad 2 Wi-Fi Black 32GB"},
{:id => 211, :name => "iPad iPad 4 (with Retina Display) Wi-Fi White 64GB"},
{:id => 212, :name => "iPad iPad 3 (New iPad)  Wi-Fi + Cellular Black 64GB"},
{:id => 213, :name => "iPad iPad Wi-Fi + Cellular 32GB"},
{:id => 214, :name => "iPad iPad Wi-Fi + Cellular 64GB"},
{:id => 215, :name => "iPhone iPhone 5 Black 16GB"},
{:id => 216, :name => "iPad iPad 2 Wi-Fi Black 64GB"},
{:id => 217, :name => "iPhone iPhone 4 White 8GB"},
{:id => 218, :name => "iPad iPad Wi-Fi + Cellular 16GB"},
{:id => 219, :name => "iPhone iPhone 3GS Black 32GB"},
{:id => 221, :name => "iPhone iPhone 4 White None"},
{:id => 223, :name => "iPhone iPhone 3G Black 8GB"},
{:id => 225, :name => "iPad iPad 4 (with Retina Display) Wi-Fi + Cellular White 64GB"},
{:id => 226, :name => "iPad iPad 2 Wi-Fi + Cellular White 16GB"},
{:id => 237, :name => "iPhone iPhone 4 Black None"},
{:id => 248, :name => "iPad iPad mini Wi-Fi + Cellular White 32GB"},
{:id => 249, :name => "iPad iPad mini Wi-Fi + Cellular White 64GB"},
{:id => 250, :name => "iPad iPad 3 (New iPad)  Wi-Fi + Cellular White 32GB"},
{:id => 251, :name => "iPad iPad 3 (New iPad)  Wi-Fi White 16GB"},
{:id => 252, :name => "iPad iPad mini Wi-Fi Black 64GB"},
{:id => 253, :name => "iPad iPad 4 (with Retina Display) Wi-Fi + Cellular Black 16GB"},
{:id => 254, :name => "iPad iPad 2 Wi-Fi + Cellular White 32GB"},
{:id => 255, :name => "iPhone iPhone 5 Black None"},
{:id => 256, :name => "iPhone iPhone 3G Black 16GB"},
{:id => 257, :name => "iPad iPad 4 (with Retina Display) Wi-Fi + Cellular Black 32GB"},
{:id => 258, :name => "iPhone iPhone 3GS White 16GB"},
{:id => 259, :name => "iPhone iPhone 3GS Black 8GB"},
{:id => 260, :name => "iPhone iPhone 3GS Black None"},
{:id => 261, :name => "iPad iPad 3 (New iPad)  Wi-Fi White 64GB"},
{:id => 262, :name => "iPad iPad 2 Wi-Fi + Cellular Black 32GB"},
{:id => 263, :name => "iPad iPad 3 (New iPad)  Wi-Fi Black 32GB"},
{:id => 264, :name => "Mac MacBook Air"},
{:id => 266, :name => "iPad iPad mini Wi-Fi Black 16GB"},
{:id => 267, :name => "iPad iPad mini Wi-Fi White 16GB"},
{:id => 268, :name => "iPad iPad 2 Wi-Fi White  64GB"},
{:id => 269, :name => "iPad iPad Wi-Fi 16GB"},
{:id => 270, :name => "iPad iPad 2 Wi-Fi Black 16GB"},
{:id => 271, :name => "iPad iPad mini Wi-Fi + Cellular Black 64GB"},
{:id => 272, :name => "iPad iPad 2 Wi-Fi White  32GB"},
{:id => 273, :name => "iPad iPad 4 (with Retina Display) Wi-Fi White 16GB"},
{:id => 274, :name => "iPad iPad 3 (New iPad)  Wi-Fi Black 16GB"},
{:id => 275, :name => "iPhone iPhone 3GS Black 16GB"},
{:id => 276, :name => "iPad iPad 3 (New iPad)  Wi-Fi + Cellular Black 16GB"},
{:id => 278, :name => "iPhone iPhone 3G Black None"},
{:id => 279, :name => "iPad iPad 3 (New iPad)  Wi-Fi White 32GB"},
{:id => 280, :name => "iPad iPad 3 (New iPad)  Wi-Fi Black 64GB"},
{:id => 282, :name => "iPad iPad 4 (with Retina Display) Wi-Fi Black 16GB"},
{:id => 283, :name => "iPad iPad Wi-Fi 64GB"},
{:id => 286, :name => "iPhone iPhone 4S Black None"},
{:id => 287, :name => "iPad iPad 4 (with Retina Display) Wi-Fi Black 32GB"},
{:id => 288, :name => "iPad iPad 4 (with Retina Display) Wi-Fi + Cellular Black 128GB"},
{:id => 289, :name => "iPad iPad Wi-Fi 32GB"},
{:id => 290, :name => "iPad iPad 3 (New iPad)  Wi-Fi + Cellular White 16GB"},
{:id => 291, :name => "iPad iPad mini Wi-Fi + Cellular Black 32GB"},
{:id => 292, :name => "Mac iMac"},
{:id => 293, :name => "iPad iPad mini Wi-Fi + Cellular White 16GB"},
{:id => 294, :name => "iPad iPad mini Wi-Fi + Cellular Black 16GB"},
{:id => 295, :name => "iPad iPad 4 (with Retina Display) Wi-Fi + Cellular White 16GB"},
{:id => 296, :name => "iPad iPad mini Wi-Fi White 64GB"},
{:id => 297, :name => "iPhone iPhone 4S White None"},
{:id => 299, :name => "iPhone iPhone 3GS White None"},
{:id => 302, :name => "iPhone iPhone 3G White 16GB"}
]

DEVICE_TYPES.each do |dt|
  if(device_type = DeviceType.search_by_full_name(dt[:name])).present?
    id1 = dt[:id]
    id2 = device_type.id
    Device.where(device_type_id: id1).find_each{|dev|dev.update_attribute(:device_type_id, id2)}
  end
end