require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CashDrawersController do

  # This should return the minimal set of attributes required to create a valid
  # CashDrawer. As you add validations to CashDrawer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CashDrawersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cash_drawers as @cash_drawers" do
      cash_drawer = CashDrawer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cash_drawers).should eq([cash_drawer])
    end
  end

  describe "GET show" do
    it "assigns the requested cash_drawer as @cash_drawer" do
      cash_drawer = CashDrawer.create! valid_attributes
      get :show, {:id => cash_drawer.to_param}, valid_session
      assigns(:cash_drawer).should eq(cash_drawer)
    end
  end

  describe "GET new" do
    it "assigns a new cash_drawer as @cash_drawer" do
      get :new, {}, valid_session
      assigns(:cash_drawer).should be_a_new(CashDrawer)
    end
  end

  describe "GET edit" do
    it "assigns the requested cash_drawer as @cash_drawer" do
      cash_drawer = CashDrawer.create! valid_attributes
      get :edit, {:id => cash_drawer.to_param}, valid_session
      assigns(:cash_drawer).should eq(cash_drawer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CashDrawer" do
        expect {
          post :create, {:cash_drawer => valid_attributes}, valid_session
        }.to change(CashDrawer, :count).by(1)
      end

      it "assigns a newly created cash_drawer as @cash_drawer" do
        post :create, {:cash_drawer => valid_attributes}, valid_session
        assigns(:cash_drawer).should be_a(CashDrawer)
        assigns(:cash_drawer).should be_persisted
      end

      it "redirects to the created cash_drawer" do
        post :create, {:cash_drawer => valid_attributes}, valid_session
        response.should redirect_to(CashDrawer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cash_drawer as @cash_drawer" do
        # Trigger the behavior that occurs when invalid params are submitted
        CashDrawer.any_instance.stub(:save).and_return(false)
        post :create, {:cash_drawer => { "name" => "invalid value" }}, valid_session
        assigns(:cash_drawer).should be_a_new(CashDrawer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CashDrawer.any_instance.stub(:save).and_return(false)
        post :create, {:cash_drawer => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cash_drawer" do
        cash_drawer = CashDrawer.create! valid_attributes
        # Assuming there are no other cash_drawers in the database, this
        # specifies that the CashDrawer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CashDrawer.any_instance.should_receive(:update_attributes).with({ "name" => "1" })
        put :update, {:id => cash_drawer.to_param, :cash_drawer => { "name" => "1" }}, valid_session
      end

      it "assigns the requested cash_drawer as @cash_drawer" do
        cash_drawer = CashDrawer.create! valid_attributes
        put :update, {:id => cash_drawer.to_param, :cash_drawer => valid_attributes}, valid_session
        assigns(:cash_drawer).should eq(cash_drawer)
      end

      it "redirects to the cash_drawer" do
        cash_drawer = CashDrawer.create! valid_attributes
        put :update, {:id => cash_drawer.to_param, :cash_drawer => valid_attributes}, valid_session
        response.should redirect_to(cash_drawer)
      end
    end

    describe "with invalid params" do
      it "assigns the cash_drawer as @cash_drawer" do
        cash_drawer = CashDrawer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CashDrawer.any_instance.stub(:save).and_return(false)
        put :update, {:id => cash_drawer.to_param, :cash_drawer => { "name" => "invalid value" }}, valid_session
        assigns(:cash_drawer).should eq(cash_drawer)
      end

      it "re-renders the 'edit' template" do
        cash_drawer = CashDrawer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CashDrawer.any_instance.stub(:save).and_return(false)
        put :update, {:id => cash_drawer.to_param, :cash_drawer => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cash_drawer" do
      cash_drawer = CashDrawer.create! valid_attributes
      expect {
        delete :destroy, {:id => cash_drawer.to_param}, valid_session
      }.to change(CashDrawer, :count).by(-1)
    end

    it "redirects to the cash_drawers list" do
      cash_drawer = CashDrawer.create! valid_attributes
      delete :destroy, {:id => cash_drawer.to_param}, valid_session
      response.should redirect_to(cash_drawers_url)
    end
  end

end
