require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FeatureValuesController do

  # This should return the minimal set of attributes required to create a valid
  # FeatureValue. As you add validations to FeatureValue, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "feature_type" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FeatureValuesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all feature_values as @feature_values" do
      feature_value = FeatureValue.create! valid_attributes
      get :index, {}, valid_session
      assigns(:feature_values).should eq([feature_value])
    end
  end

  describe "GET show" do
    it "assigns the requested feature_value as @feature_value" do
      feature_value = FeatureValue.create! valid_attributes
      get :show, {:id => feature_value.to_param}, valid_session
      assigns(:feature_value).should eq(feature_value)
    end
  end

  describe "GET new" do
    it "assigns a new feature_value as @feature_value" do
      get :new, {}, valid_session
      assigns(:feature_value).should be_a_new(FeatureValue)
    end
  end

  describe "GET edit" do
    it "assigns the requested feature_value as @feature_value" do
      feature_value = FeatureValue.create! valid_attributes
      get :edit, {:id => feature_value.to_param}, valid_session
      assigns(:feature_value).should eq(feature_value)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FeatureValue" do
        expect {
          post :create, {:feature_value => valid_attributes}, valid_session
        }.to change(FeatureValue, :count).by(1)
      end

      it "assigns a newly created feature_value as @feature_value" do
        post :create, {:feature_value => valid_attributes}, valid_session
        assigns(:feature_value).should be_a(FeatureValue)
        assigns(:feature_value).should be_persisted
      end

      it "redirects to the created feature_value" do
        post :create, {:feature_value => valid_attributes}, valid_session
        response.should redirect_to(FeatureValue.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved feature_value as @feature_value" do
        # Trigger the behavior that occurs when invalid params are submitted
        FeatureValue.any_instance.stub(:save).and_return(false)
        post :create, {:feature_value => { "feature_type" => "invalid value" }}, valid_session
        assigns(:feature_value).should be_a_new(FeatureValue)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FeatureValue.any_instance.stub(:save).and_return(false)
        post :create, {:feature_value => { "feature_type" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested feature_value" do
        feature_value = FeatureValue.create! valid_attributes
        # Assuming there are no other feature_values in the database, this
        # specifies that the FeatureValue created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FeatureValue.any_instance.should_receive(:update_attributes).with({ "feature_type" => "" })
        put :update, {:id => feature_value.to_param, :feature_value => { "feature_type" => "" }}, valid_session
      end

      it "assigns the requested feature_value as @feature_value" do
        feature_value = FeatureValue.create! valid_attributes
        put :update, {:id => feature_value.to_param, :feature_value => valid_attributes}, valid_session
        assigns(:feature_value).should eq(feature_value)
      end

      it "redirects to the feature_value" do
        feature_value = FeatureValue.create! valid_attributes
        put :update, {:id => feature_value.to_param, :feature_value => valid_attributes}, valid_session
        response.should redirect_to(feature_value)
      end
    end

    describe "with invalid params" do
      it "assigns the feature_value as @feature_value" do
        feature_value = FeatureValue.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FeatureValue.any_instance.stub(:save).and_return(false)
        put :update, {:id => feature_value.to_param, :feature_value => { "feature_type" => "invalid value" }}, valid_session
        assigns(:feature_value).should eq(feature_value)
      end

      it "re-renders the 'edit' template" do
        feature_value = FeatureValue.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FeatureValue.any_instance.stub(:save).and_return(false)
        put :update, {:id => feature_value.to_param, :feature_value => { "feature_type" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested feature_value" do
      feature_value = FeatureValue.create! valid_attributes
      expect {
        delete :destroy, {:id => feature_value.to_param}, valid_session
      }.to change(FeatureValue, :count).by(-1)
    end

    it "redirects to the feature_values list" do
      feature_value = FeatureValue.create! valid_attributes
      delete :destroy, {:id => feature_value.to_param}, valid_session
      response.should redirect_to(feature_values_url)
    end
  end

end
