require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QuickOrdersController do

  # This should return the minimal set of attributes required to create a valid
  # QuickOrder. As you add validations to QuickOrder, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "number" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QuickOrdersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all quick_orders as @quick_orders" do
      quick_order = QuickOrder.create! valid_attributes
      get :index, {}, valid_session
      assigns(:quick_orders).should eq([quick_order])
    end
  end

  describe "GET show" do
    it "assigns the requested quick_order as @quick_order" do
      quick_order = QuickOrder.create! valid_attributes
      get :show, {:id => quick_order.to_param}, valid_session
      assigns(:quick_order).should eq(quick_order)
    end
  end

  describe "GET new" do
    it "assigns a new quick_order as @quick_order" do
      get :new, {}, valid_session
      assigns(:quick_order).should be_a_new(QuickOrder)
    end
  end

  describe "GET edit" do
    it "assigns the requested quick_order as @quick_order" do
      quick_order = QuickOrder.create! valid_attributes
      get :edit, {:id => quick_order.to_param}, valid_session
      assigns(:quick_order).should eq(quick_order)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new QuickOrder" do
        expect {
          post :create, {:quick_order => valid_attributes}, valid_session
        }.to change(QuickOrder, :count).by(1)
      end

      it "assigns a newly created quick_order as @quick_order" do
        post :create, {:quick_order => valid_attributes}, valid_session
        assigns(:quick_order).should be_a(QuickOrder)
        assigns(:quick_order).should be_persisted
      end

      it "redirects to the created quick_order" do
        post :create, {:quick_order => valid_attributes}, valid_session
        response.should redirect_to(QuickOrder.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved quick_order as @quick_order" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuickOrder.any_instance.stub(:save).and_return(false)
        post :create, {:quick_order => { "number" => "invalid value" }}, valid_session
        assigns(:quick_order).should be_a_new(QuickOrder)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuickOrder.any_instance.stub(:save).and_return(false)
        post :create, {:quick_order => { "number" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested quick_order" do
        quick_order = QuickOrder.create! valid_attributes
        # Assuming there are no other quick_orders in the database, this
        # specifies that the QuickOrder created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        QuickOrder.any_instance.should_receive(:update_attributes).with({ "number" => "1" })
        put :update, {:id => quick_order.to_param, :quick_order => { "number" => "1" }}, valid_session
      end

      it "assigns the requested quick_order as @quick_order" do
        quick_order = QuickOrder.create! valid_attributes
        put :update, {:id => quick_order.to_param, :quick_order => valid_attributes}, valid_session
        assigns(:quick_order).should eq(quick_order)
      end

      it "redirects to the quick_order" do
        quick_order = QuickOrder.create! valid_attributes
        put :update, {:id => quick_order.to_param, :quick_order => valid_attributes}, valid_session
        response.should redirect_to(quick_order)
      end
    end

    describe "with invalid params" do
      it "assigns the quick_order as @quick_order" do
        quick_order = QuickOrder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuickOrder.any_instance.stub(:save).and_return(false)
        put :update, {:id => quick_order.to_param, :quick_order => { "number" => "invalid value" }}, valid_session
        assigns(:quick_order).should eq(quick_order)
      end

      it "re-renders the 'edit' template" do
        quick_order = QuickOrder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuickOrder.any_instance.stub(:save).and_return(false)
        put :update, {:id => quick_order.to_param, :quick_order => { "number" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested quick_order" do
      quick_order = QuickOrder.create! valid_attributes
      expect {
        delete :destroy, {:id => quick_order.to_param}, valid_session
      }.to change(QuickOrder, :count).by(-1)
    end

    it "redirects to the quick_orders list" do
      quick_order = QuickOrder.create! valid_attributes
      delete :destroy, {:id => quick_order.to_param}, valid_session
      response.should redirect_to(quick_orders_url)
    end
  end

end
