require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QuickTasksController do

  # This should return the minimal set of attributes required to create a valid
  # QuickTask. As you add validations to QuickTask, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QuickTasksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all quick_tasks as @quick_tasks" do
      quick_task = QuickTask.create! valid_attributes
      get :index, {}, valid_session
      assigns(:quick_tasks).should eq([quick_task])
    end
  end

  describe "GET show" do
    it "assigns the requested quick_task as @quick_task" do
      quick_task = QuickTask.create! valid_attributes
      get :show, {:id => quick_task.to_param}, valid_session
      assigns(:quick_task).should eq(quick_task)
    end
  end

  describe "GET new" do
    it "assigns a new quick_task as @quick_task" do
      get :new, {}, valid_session
      assigns(:quick_task).should be_a_new(QuickTask)
    end
  end

  describe "GET edit" do
    it "assigns the requested quick_task as @quick_task" do
      quick_task = QuickTask.create! valid_attributes
      get :edit, {:id => quick_task.to_param}, valid_session
      assigns(:quick_task).should eq(quick_task)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new QuickTask" do
        expect {
          post :create, {:quick_task => valid_attributes}, valid_session
        }.to change(QuickTask, :count).by(1)
      end

      it "assigns a newly created quick_task as @quick_task" do
        post :create, {:quick_task => valid_attributes}, valid_session
        assigns(:quick_task).should be_a(QuickTask)
        assigns(:quick_task).should be_persisted
      end

      it "redirects to the created quick_task" do
        post :create, {:quick_task => valid_attributes}, valid_session
        response.should redirect_to(QuickTask.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved quick_task as @quick_task" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuickTask.any_instance.stub(:save).and_return(false)
        post :create, {:quick_task => { "name" => "invalid value" }}, valid_session
        assigns(:quick_task).should be_a_new(QuickTask)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuickTask.any_instance.stub(:save).and_return(false)
        post :create, {:quick_task => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested quick_task" do
        quick_task = QuickTask.create! valid_attributes
        # Assuming there are no other quick_tasks in the database, this
        # specifies that the QuickTask created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        QuickTask.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => quick_task.to_param, :quick_task => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested quick_task as @quick_task" do
        quick_task = QuickTask.create! valid_attributes
        put :update, {:id => quick_task.to_param, :quick_task => valid_attributes}, valid_session
        assigns(:quick_task).should eq(quick_task)
      end

      it "redirects to the quick_task" do
        quick_task = QuickTask.create! valid_attributes
        put :update, {:id => quick_task.to_param, :quick_task => valid_attributes}, valid_session
        response.should redirect_to(quick_task)
      end
    end

    describe "with invalid params" do
      it "assigns the quick_task as @quick_task" do
        quick_task = QuickTask.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuickTask.any_instance.stub(:save).and_return(false)
        put :update, {:id => quick_task.to_param, :quick_task => { "name" => "invalid value" }}, valid_session
        assigns(:quick_task).should eq(quick_task)
      end

      it "re-renders the 'edit' template" do
        quick_task = QuickTask.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuickTask.any_instance.stub(:save).and_return(false)
        put :update, {:id => quick_task.to_param, :quick_task => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested quick_task" do
      quick_task = QuickTask.create! valid_attributes
      expect {
        delete :destroy, {:id => quick_task.to_param}, valid_session
      }.to change(QuickTask, :count).by(-1)
    end

    it "redirects to the quick_tasks list" do
      quick_task = QuickTask.create! valid_attributes
      delete :destroy, {:id => quick_task.to_param}, valid_session
      response.should redirect_to(quick_tasks_url)
    end
  end

end
