require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SpairPartsController do

  # This should return the minimal set of attributes required to create a valid
  # SpairPart. As you add validations to SpairPart, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "repair_service" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SpairPartsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all spair_parts as @spair_parts" do
      spair_part = SpairPart.create! valid_attributes
      get :index, {}, valid_session
      assigns(:spair_parts).should eq([spair_part])
    end
  end

  describe "GET show" do
    it "assigns the requested spair_part as @spair_part" do
      spair_part = SpairPart.create! valid_attributes
      get :show, {:id => spair_part.to_param}, valid_session
      assigns(:spair_part).should eq(spair_part)
    end
  end

  describe "GET new" do
    it "assigns a new spair_part as @spair_part" do
      get :new, {}, valid_session
      assigns(:spair_part).should be_a_new(SpairPart)
    end
  end

  describe "GET edit" do
    it "assigns the requested spair_part as @spair_part" do
      spair_part = SpairPart.create! valid_attributes
      get :edit, {:id => spair_part.to_param}, valid_session
      assigns(:spair_part).should eq(spair_part)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SpairPart" do
        expect {
          post :create, {:spair_part => valid_attributes}, valid_session
        }.to change(SpairPart, :count).by(1)
      end

      it "assigns a newly created spair_part as @spair_part" do
        post :create, {:spair_part => valid_attributes}, valid_session
        assigns(:spair_part).should be_a(SpairPart)
        assigns(:spair_part).should be_persisted
      end

      it "redirects to the created spair_part" do
        post :create, {:spair_part => valid_attributes}, valid_session
        response.should redirect_to(SpairPart.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved spair_part as @spair_part" do
        # Trigger the behavior that occurs when invalid params are submitted
        SpairPart.any_instance.stub(:save).and_return(false)
        post :create, {:spair_part => { "repair_service" => "invalid value" }}, valid_session
        assigns(:spair_part).should be_a_new(SpairPart)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SpairPart.any_instance.stub(:save).and_return(false)
        post :create, {:spair_part => { "repair_service" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested spair_part" do
        spair_part = SpairPart.create! valid_attributes
        # Assuming there are no other spair_parts in the database, this
        # specifies that the SpairPart created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SpairPart.any_instance.should_receive(:update_attributes).with({ "repair_service" => "" })
        put :update, {:id => spair_part.to_param, :spair_part => { "repair_service" => "" }}, valid_session
      end

      it "assigns the requested spair_part as @spair_part" do
        spair_part = SpairPart.create! valid_attributes
        put :update, {:id => spair_part.to_param, :spair_part => valid_attributes}, valid_session
        assigns(:spair_part).should eq(spair_part)
      end

      it "redirects to the spair_part" do
        spair_part = SpairPart.create! valid_attributes
        put :update, {:id => spair_part.to_param, :spair_part => valid_attributes}, valid_session
        response.should redirect_to(spair_part)
      end
    end

    describe "with invalid params" do
      it "assigns the spair_part as @spair_part" do
        spair_part = SpairPart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SpairPart.any_instance.stub(:save).and_return(false)
        put :update, {:id => spair_part.to_param, :spair_part => { "repair_service" => "invalid value" }}, valid_session
        assigns(:spair_part).should eq(spair_part)
      end

      it "re-renders the 'edit' template" do
        spair_part = SpairPart.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SpairPart.any_instance.stub(:save).and_return(false)
        put :update, {:id => spair_part.to_param, :spair_part => { "repair_service" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested spair_part" do
      spair_part = SpairPart.create! valid_attributes
      expect {
        delete :destroy, {:id => spair_part.to_param}, valid_session
      }.to change(SpairPart, :count).by(-1)
    end

    it "redirects to the spair_parts list" do
      spair_part = SpairPart.create! valid_attributes
      delete :destroy, {:id => spair_part.to_param}, valid_session
      response.should redirect_to(spair_parts_url)
    end
  end

end
