require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TopSalablesController do

  # This should return the minimal set of attributes required to create a valid
  # TopSalable. As you add validations to TopSalable, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "salable" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TopSalablesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all top_salables as @top_salables" do
      top_salable = TopSalable.create! valid_attributes
      get :index, {}, valid_session
      assigns(:top_salables).should eq([top_salable])
    end
  end

  describe "GET show" do
    it "assigns the requested top_salable as @top_salable" do
      top_salable = TopSalable.create! valid_attributes
      get :show, {:id => top_salable.to_param}, valid_session
      assigns(:top_salable).should eq(top_salable)
    end
  end

  describe "GET new" do
    it "assigns a new top_salable as @top_salable" do
      get :new, {}, valid_session
      assigns(:top_salable).should be_a_new(TopSalable)
    end
  end

  describe "GET edit" do
    it "assigns the requested top_salable as @top_salable" do
      top_salable = TopSalable.create! valid_attributes
      get :edit, {:id => top_salable.to_param}, valid_session
      assigns(:top_salable).should eq(top_salable)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TopSalable" do
        expect {
          post :create, {:top_salable => valid_attributes}, valid_session
        }.to change(TopSalable, :count).by(1)
      end

      it "assigns a newly created top_salable as @top_salable" do
        post :create, {:top_salable => valid_attributes}, valid_session
        assigns(:top_salable).should be_a(TopSalable)
        assigns(:top_salable).should be_persisted
      end

      it "redirects to the created top_salable" do
        post :create, {:top_salable => valid_attributes}, valid_session
        response.should redirect_to(TopSalable.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved top_salable as @top_salable" do
        # Trigger the behavior that occurs when invalid params are submitted
        TopSalable.any_instance.stub(:save).and_return(false)
        post :create, {:top_salable => { "salable" => "invalid value" }}, valid_session
        assigns(:top_salable).should be_a_new(TopSalable)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TopSalable.any_instance.stub(:save).and_return(false)
        post :create, {:top_salable => { "salable" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested top_salable" do
        top_salable = TopSalable.create! valid_attributes
        # Assuming there are no other top_salables in the database, this
        # specifies that the TopSalable created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TopSalable.any_instance.should_receive(:update_attributes).with({ "salable" => "" })
        put :update, {:id => top_salable.to_param, :top_salable => { "salable" => "" }}, valid_session
      end

      it "assigns the requested top_salable as @top_salable" do
        top_salable = TopSalable.create! valid_attributes
        put :update, {:id => top_salable.to_param, :top_salable => valid_attributes}, valid_session
        assigns(:top_salable).should eq(top_salable)
      end

      it "redirects to the top_salable" do
        top_salable = TopSalable.create! valid_attributes
        put :update, {:id => top_salable.to_param, :top_salable => valid_attributes}, valid_session
        response.should redirect_to(top_salable)
      end
    end

    describe "with invalid params" do
      it "assigns the top_salable as @top_salable" do
        top_salable = TopSalable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TopSalable.any_instance.stub(:save).and_return(false)
        put :update, {:id => top_salable.to_param, :top_salable => { "salable" => "invalid value" }}, valid_session
        assigns(:top_salable).should eq(top_salable)
      end

      it "re-renders the 'edit' template" do
        top_salable = TopSalable.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TopSalable.any_instance.stub(:save).and_return(false)
        put :update, {:id => top_salable.to_param, :top_salable => { "salable" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested top_salable" do
      top_salable = TopSalable.create! valid_attributes
      expect {
        delete :destroy, {:id => top_salable.to_param}, valid_session
      }.to change(TopSalable, :count).by(-1)
    end

    it "redirects to the top_salables list" do
      top_salable = TopSalable.create! valid_attributes
      delete :destroy, {:id => top_salable.to_param}, valid_session
      response.should redirect_to(top_salables_url)
    end
  end

end
